// This file is auto generated. Please, don't manually change this file

#ifndef GHERKIN_DIALECT_CC_
#define GHERKIN_DIALECT_CC_
#include "dialect.h"

static const Dialect DIALECTS[] = {
  {
    1,
    22,
    "af",
    {U"En "},
    {U"Agtergrond"},
    {U"Maar "},
    {U"Voorbeelde"},
    {U"Funksie",U"Besigheid Behoefte",U"Vermoë"},
    {U"Gegewe "},
    {U"Regel"},
    {U"Voorbeeld",U"Situasie"},
    {U"Situasie Uiteensetting"},
    {U"Dan "},
    {U"Wanneer "},
  },
  {
    2,
    19,
    "am",
    {U"Եվ "},
    {U"Կոնտեքստ"},
    {U"Բայց "},
    {U"Օրինակներ"},
    {U"Ֆունկցիոնալություն",U"Հատկություն"},
    {U"Դիցուք "},
    {U"Rule"},
    {U"Օրինակ",U"Սցենար"},
    {U"Սցենարի կառուցվացքը"},
    {U"Ապա "},
    {U"Եթե ",U"Երբ "},
  },
  {
    3,
    16,
    "an",
    {U"Y ",U"E "},
    {U"Antecedents"},
    {U"Pero "},
    {U"Eixemplos"},
    {U"Caracteristica"},
    {U"Dau ",U"Dada ",U"Daus ",U"Dadas "},
    {U"Rule"},
    {U"Eixemplo",U"Caso"},
    {U"Esquema del caso"},
    {U"Alavez ",U"Allora ",U"Antonces "},
    {U"Cuan "},
  },
  {
    4,
    12,
    "ar",
    {U"و "},
    {U"الخلفية"},
    {U"لكن "},
    {U"امثلة"},
    {U"خاصية"},
    {U"بفرض "},
    {U"Rule"},
    {U"مثال",U"سيناريو"},
    {U"سيناريو مخطط"},
    {U"اذاً ",U"ثم "},
    {U"متى ",U"عندما "},
  },
  {
    5,
    15,
    "ast",
    {U"Y ",U"Ya "},
    {U"Antecedentes"},
    {U"Peru "},
    {U"Exemplos"},
    {U"Carauterística"},
    {U"Dáu ",U"Dada ",U"Daos ",U"Daes "},
    {U"Rule"},
    {U"Exemplo",U"Casu"},
    {U"Esbozu del casu"},
    {U"Entós "},
    {U"Cuando "},
  },
  {
    6,
    20,
    "az",
    {U"Və ",U"Həm "},
    {U"Keçmiş",U"Kontekst"},
    {U"Amma ",U"Ancaq "},
    {U"Nümunələr"},
    {U"Özəllik"},
    {U"Tutaq ki ",U"Verilir "},
    {U"Rule"},
    {U"Nümunə",U"Ssenari"},
    {U"Ssenarinin strukturu"},
    {U"O halda "},
    {U"Əgər ",U"Nə vaxt ki "},
  },
  {
    7,
    16,
    "be",
    {U"I ",U"Ды ",U"Таксама "},
    {U"Кантэкст"},
    {U"Але ",U"Інакш "},
    {U"Прыклады"},
    {U"Функцыянальнасць",U"Фіча"},
    {U"Няхай ",U"Дадзена "},
    {U"Правілы"},
    {U"Сцэнарый",U"Cцэнар"},
    {U"Шаблон сцэнарыя",U"Узор сцэнара"},
    {U"Тады "},
    {U"Калі "},
  },
  {
    8,
    17,
    "bg",
    {U"И "},
    {U"Предистория"},
    {U"Но "},
    {U"Примери"},
    {U"Функционалност"},
    {U"Дадено "},
    {U"Правило"},
    {U"Пример",U"Сценарий"},
    {U"Рамка на сценарий"},
    {U"То "},
    {U"Когато "},
  },
  {
    9,
    21,
    "bm",
    {U"Dan "},
    {U"Latar Belakang"},
    {U"Tetapi ",U"Tapi "},
    {U"Contoh"},
    {U"Fungsi"},
    {U"Diberi ",U"Bagi "},
    {U"Rule"},
    {U"Senario",U"Situasi",U"Keadaan"},
    {U"Kerangka Senario",U"Kerangka Situasi",U"Kerangka Keadaan",U"Garis Panduan Senario"},
    {U"Maka ",U"Kemudian "},
    {U"Apabila "},
  },
  {
    10,
    16,
    "bs",
    {U"I ",U"A "},
    {U"Pozadina"},
    {U"Ali "},
    {U"Primjeri"},
    {U"Karakteristika"},
    {U"Dato "},
    {U"Rule"},
    {U"Primjer",U"Scenariju",U"Scenario"},
    {U"Scenariju-obris",U"Scenario-outline"},
    {U"Zatim "},
    {U"Kada "},
  },
  {
    11,
    21,
    "ca",
    {U"I "},
    {U"Rerefons",U"Antecedents"},
    {U"Però "},
    {U"Exemples"},
    {U"Característica",U"Funcionalitat"},
    {U"Donat ",U"Donada ",U"Atès ",U"Atesa "},
    {U"Rule"},
    {U"Exemple",U"Escenari"},
    {U"Esquema de l'escenari"},
    {U"Aleshores ",U"Cal "},
    {U"Quan "},
  },
  {
    12,
    15,
    "cs",
    {U"A také ",U"A "},
    {U"Pozadí",U"Kontext"},
    {U"Ale "},
    {U"Příklady"},
    {U"Požadavek"},
    {U"Pokud ",U"Za předpokladu "},
    {U"Pravidlo"},
    {U"Příklad",U"Scénář"},
    {U"Náčrt Scénáře",U"Osnova scénáře"},
    {U"Pak "},
    {U"Když "},
  },
  {
    13,
    19,
    "cy-GB",
    {U"A "},
    {U"Cefndir"},
    {U"Ond "},
    {U"Enghreifftiau"},
    {U"Arwedd"},
    {U"Anrhegedig a "},
    {U"Rule"},
    {U"Enghraifft",U"Scenario"},
    {U"Scenario Amlinellol"},
    {U"Yna "},
    {U"Pryd "},
  },
  {
    14,
    17,
    "da",
    {U"Og "},
    {U"Baggrund"},
    {U"Men "},
    {U"Eksempler"},
    {U"Egenskab"},
    {U"Givet "},
    {U"Rule"},
    {U"Eksempel",U"Scenarie"},
    {U"Abstrakt Scenario"},
    {U"Så "},
    {U"Når "},
  },
  {
    15,
    17,
    "de",
    {U"Und "},
    {U"Grundlage",U"Hintergrund",U"Voraussetzungen",U"Vorbedingungen"},
    {U"Aber "},
    {U"Beispiele"},
    {U"Funktionalität",U"Funktion"},
    {U"Angenommen ",U"Gegeben sei ",U"Gegeben seien "},
    {U"Rule",U"Regel"},
    {U"Beispiel",U"Szenario"},
    {U"Szenariogrundriss",U"Szenarien"},
    {U"Dann "},
    {U"Wenn "},
  },
  {
    16,
    19,
    "el",
    {U"Και "},
    {U"Υπόβαθρο"},
    {U"Αλλά "},
    {U"Παραδείγματα",U"Σενάρια"},
    {U"Δυνατότητα",U"Λειτουργία"},
    {U"Δεδομένου "},
    {U"Rule"},
    {U"Παράδειγμα",U"Σενάριο"},
    {U"Περιγραφή Σεναρίου",U"Περίγραμμα Σεναρίου"},
    {U"Τότε "},
    {U"Όταν "},
  },
  {
    17,
    4,
    "em",
    {U"😂"},
    {U"💤"},
    {U"😔"},
    {U"📓"},
    {U"📚"},
    {U"😐"},
    {U"Rule"},
    {U"🥒",U"📕"},
    {U"📖"},
    {U"🙏"},
    {U"🎬"},
  },
  {
    18,
    17,
    "en",
    {U"And "},
    {U"Background"},
    {U"But "},
    {U"Examples",U"Scenarios"},
    {U"Feature",U"Business Need",U"Ability"},
    {U"Given "},
    {U"Rule"},
    {U"Example",U"Scenario"},
    {U"Scenario Outline",U"Scenario Template"},
    {U"Then "},
    {U"When "},
  },
  {
    19,
    26,
    "en-Scouse",
    {U"An "},
    {U"Dis is what went down"},
    {U"Buh "},
    {U"Examples"},
    {U"Feature"},
    {U"Givun ",U"Youse know when youse got "},
    {U"Rule"},
    {U"The thing of it is"},
    {U"Wharrimean is"},
    {U"Dun ",U"Den youse gotta "},
    {U"Wun ",U"Youse know like when "},
  },
  {
    20,
    35,
    "en-au",
    {U"Too right "},
    {U"First off"},
    {U"Yeah nah "},
    {U"You'll wanna"},
    {U"Pretty much"},
    {U"Y'know "},
    {U"Rule"},
    {U"Awww, look mate"},
    {U"Reckon it's like"},
    {U"But at the end of the day I reckon "},
    {U"It's just unbelievable "},
  },
  {
    21,
    12,
    "en-lol",
    {U"AN "},
    {U"B4"},
    {U"BUT "},
    {U"EXAMPLZ"},
    {U"OH HAI"},
    {U"I CAN HAZ "},
    {U"Rule"},
    {U"MISHUN"},
    {U"MISHUN SRSLY"},
    {U"DEN "},
    {U"WEN "},
  },
  {
    22,
    13,
    "en-old",
    {U"Ond ",U"7 "},
    {U"Aer",U"Ær"},
    {U"Ac "},
    {U"Se the",U"Se þe",U"Se ðe"},
    {U"Hwaet",U"Hwæt"},
    {U"Thurh ",U"Þurh ",U"Ðurh "},
    {U"Rule"},
    {U"Swa"},
    {U"Swa hwaer swa",U"Swa hwær swa"},
    {U"Tha ",U"Þa ",U"Ða ",U"Tha the ",U"Þa þe ",U"Ða ðe "},
    {U"Bæþsealf ",U"Bæþsealfa ",U"Bæþsealfe ",U"Ciricæw ",U"Ciricæwe ",U"Ciricæwa "},
  },
  {
    23,
    22,
    "en-pirate",
    {U"Aye "},
    {U"Yo-ho-ho"},
    {U"Avast! "},
    {U"Dead men tell no tales"},
    {U"Ahoy matey!"},
    {U"Gangway! "},
    {U"Rule"},
    {U"Heave to"},
    {U"Shiver me timbers"},
    {U"Let go and haul "},
    {U"Blimey! "},
  },
  {
    24,
    53,
    "en-tx",
    {U"Come hell or high water "},
    {U"Lemme tell y'all a story"},
    {U"Well now hold on, I'll you what "},
    {U"Now that's a story longer than a cattle drive in July"},
    {U"This ain’t my first rodeo",U"All gussied up"},
    {U"Fixin' to ",U"All git out "},
    {U"Rule "},
    {U"All hat and no cattle"},
    {U"Serious as a snake bite",U"Busy as a hound in flea season"},
    {U"There’s no tree but bears some fruit "},
    {U"Quick out of the chute "},
  },
  {
    25,
    21,
    "eo",
    {U"Kaj "},
    {U"Fono"},
    {U"Sed "},
    {U"Ekzemploj"},
    {U"Trajto"},
    {U"Donitaĵo ",U"Komence "},
    {U"Rule"},
    {U"Ekzemplo",U"Scenaro",U"Kazo"},
    {U"Konturo de la scenaro",U"Skizo",U"Kazo-skizo"},
    {U"Do "},
    {U"Se "},
  },
  {
    26,
    21,
    "es",
    {U"Y ",U"E "},
    {U"Antecedentes"},
    {U"Pero "},
    {U"Ejemplos"},
    {U"Característica",U"Necesidad del negocio",U"Requisito"},
    {U"Dado ",U"Dada ",U"Dados ",U"Dadas "},
    {U"Regla",U"Regla de negocio"},
    {U"Ejemplo",U"Escenario"},
    {U"Esquema del escenario"},
    {U"Entonces "},
    {U"Cuando "},
  },
  {
    27,
    15,
    "et",
    {U"Ja "},
    {U"Taust"},
    {U"Kuid "},
    {U"Juhtumid"},
    {U"Omadus"},
    {U"Eeldades "},
    {U"Reegel"},
    {U"Juhtum",U"Stsenaarium"},
    {U"Raamjuhtum",U"Raamstsenaarium"},
    {U"Siis "},
    {U"Kui "},
  },
  {
    28,
    12,
    "fa",
    {U"و "},
    {U"زمینه"},
    {U"اما "},
    {U"نمونه ها"},
    {U"وِیژگی"},
    {U"با فرض "},
    {U"Rule"},
    {U"مثال",U"سناریو"},
    {U"الگوی سناریو"},
    {U"آنگاه "},
    {U"هنگامی "},
  },
  {
    29,
    11,
    "fi",
    {U"Ja "},
    {U"Tausta"},
    {U"Mutta "},
    {U"Tapaukset"},
    {U"Ominaisuus"},
    {U"Oletetaan "},
    {U"Rule"},
    {U"Tapaus"},
    {U"Tapausaihio"},
    {U"Niin "},
    {U"Kun "},
  },
  {
    30,
    16,
    "fr",
    {U"Et que ",U"Et qu'",U"Et "},
    {U"Contexte"},
    {U"Mais que ",U"Mais qu'",U"Mais "},
    {U"Exemples"},
    {U"Fonctionnalité"},
    {U"Soit ",U"Sachant que ",U"Sachant qu'",U"Sachant ",U"Etant donné que ",U"Etant donné qu'",U"Etant donné ",U"Etant donnée ",U"Etant donnés ",U"Etant données ",U"Étant donné que ",U"Étant donné qu'",U"Étant donné ",U"Étant donnée ",U"Étant donnés ",U"Étant données "},
    {U"Règle"},
    {U"Exemple",U"Scénario"},
    {U"Plan du scénario",U"Plan du Scénario"},
    {U"Alors ",U"Donc "},
    {U"Quand ",U"Lorsque ",U"Lorsqu'"},
  },
  {
    31,
    16,
    "ga",
    {U"Agus"},
    {U"Cúlra"},
    {U"Ach"},
    {U"Samplaí"},
    {U"Gné"},
    {U"Cuir i gcás go",U"Cuir i gcás nach",U"Cuir i gcás gur",U"Cuir i gcás nár"},
    {U"Rule"},
    {U"Sampla",U"Cás"},
    {U"Cás Achomair"},
    {U"Ansin"},
    {U"Nuair a",U"Nuair nach",U"Nuair ba",U"Nuair nár"},
  },
  {
    32,
    17,
    "gj",
    {U"અને "},
    {U"બેકગ્રાઉન્ડ"},
    {U"પણ "},
    {U"ઉદાહરણો"},
    {U"લક્ષણ",U"વ્યાપાર જરૂર",U"ક્ષમતા"},
    {U"આપેલ છે "},
    {U"Rule"},
    {U"ઉદાહરણ",U"સ્થિતિ"},
    {U"પરિદ્દશ્ય રૂપરેખા",U"પરિદ્દશ્ય ઢાંચો"},
    {U"પછી "},
    {U"ક્યારે "},
  },
  {
    33,
    19,
    "gl",
    {U"E "},
    {U"Contexto"},
    {U"Mais ",U"Pero "},
    {U"Exemplos"},
    {U"Característica"},
    {U"Dado ",U"Dada ",U"Dados ",U"Dadas "},
    {U"Rule"},
    {U"Exemplo",U"Escenario"},
    {U"Esbozo do escenario"},
    {U"Entón ",U"Logo "},
    {U"Cando "},
  },
  {
    34,
    11,
    "he",
    {U"וגם "},
    {U"רקע"},
    {U"אבל "},
    {U"דוגמאות"},
    {U"תכונה"},
    {U"בהינתן "},
    {U"כלל"},
    {U"דוגמא",U"תרחיש"},
    {U"תבנית תרחיש"},
    {U"אז ",U"אזי "},
    {U"כאשר "},
  },
  {
    35,
    16,
    "hi",
    {U"और ",U"तथा "},
    {U"पृष्ठभूमि"},
    {U"पर ",U"परन्तु ",U"किन्तु "},
    {U"उदाहरण"},
    {U"रूप लेख"},
    {U"अगर ",U"यदि ",U"चूंकि "},
    {U"नियम"},
    {U"परिदृश्य"},
    {U"परिदृश्य रूपरेखा"},
    {U"तब ",U"तदा "},
    {U"जब ",U"कदा "},
  },
  {
    36,
    9,
    "hr",
    {U"I "},
    {U"Pozadina"},
    {U"Ali "},
    {U"Primjeri",U"Scenariji"},
    {U"Osobina",U"Mogućnost",U"Mogucnost"},
    {U"Zadan ",U"Zadani ",U"Zadano ",U"Ukoliko "},
    {U"Rule"},
    {U"Primjer",U"Scenarij"},
    {U"Skica",U"Koncept"},
    {U"Onda "},
    {U"Kada ",U"Kad "},
  },
  {
    37,
    19,
    "ht",
    {U"Ak ",U"Epi ",U"E "},
    {U"Kontèks",U"Istorik"},
    {U"Men "},
    {U"Egzanp"},
    {U"Karakteristik",U"Mak",U"Fonksyonalite"},
    {U"Sipoze ",U"Sipoze ke ",U"Sipoze Ke "},
    {U"Rule"},
    {U"Senaryo"},
    {U"Plan senaryo",U"Plan Senaryo",U"Senaryo deskripsyon",U"Senaryo Deskripsyon",U"Dyagram senaryo",U"Dyagram Senaryo"},
    {U"Lè sa a ",U"Le sa a "},
    {U"Lè ",U"Le "},
  },
  {
    38,
    19,
    "hu",
    {U"És "},
    {U"Háttér"},
    {U"De "},
    {U"Példák"},
    {U"Jellemző"},
    {U"Amennyiben ",U"Adott "},
    {U"Szabály"},
    {U"Példa",U"Forgatókönyv"},
    {U"Forgatókönyv vázlat"},
    {U"Akkor "},
    {U"Majd ",U"Ha ",U"Amikor "},
  },
  {
    39,
    20,
    "id",
    {U"Dan "},
    {U"Dasar",U"Latar Belakang"},
    {U"Tapi ",U"Tetapi "},
    {U"Contoh",U"Misal"},
    {U"Fitur"},
    {U"Dengan ",U"Diketahui ",U"Diasumsikan ",U"Bila ",U"Jika "},
    {U"Rule",U"Aturan"},
    {U"Skenario"},
    {U"Skenario konsep",U"Garis-Besar Skenario"},
    {U"Maka ",U"Kemudian "},
    {U"Ketika "},
  },
  {
    40,
    19,
    "is",
    {U"Og "},
    {U"Bakgrunnur"},
    {U"En "},
    {U"Dæmi",U"Atburðarásir"},
    {U"Eiginleiki"},
    {U"Ef "},
    {U"Rule"},
    {U"Atburðarás"},
    {U"Lýsing Atburðarásar",U"Lýsing Dæma"},
    {U"Þá "},
    {U"Þegar "},
  },
  {
    41,
    21,
    "it",
    {U"E "},
    {U"Contesto"},
    {U"Ma "},
    {U"Esempi"},
    {U"Funzionalità",U"Esigenza di Business",U"Abilità"},
    {U"Dato ",U"Data ",U"Dati ",U"Date "},
    {U"Regola"},
    {U"Esempio",U"Scenario"},
    {U"Schema dello scenario"},
    {U"Allora "},
    {U"Quando "},
  },
  {
    42,
    10,
    "ja",
    {U"且つ",U"かつ"},
    {U"背景"},
    {U"然し",U"しかし",U"但し",U"ただし"},
    {U"例",U"サンプル"},
    {U"フィーチャ",U"機能"},
    {U"前提"},
    {U"ルール"},
    {U"シナリオ"},
    {U"シナリオアウトライン",U"シナリオテンプレート",U"テンプレ",U"シナリオテンプレ"},
    {U"ならば"},
    {U"もし"},
  },
  {
    43,
    15,
    "jv",
    {U"Lan "},
    {U"Dasar"},
    {U"Tapi ",U"Nanging ",U"Ananging "},
    {U"Conto",U"Contone"},
    {U"Fitur"},
    {U"Nalika ",U"Nalikaning "},
    {U"Rule"},
    {U"Skenario"},
    {U"Konsep skenario"},
    {U"Njuk ",U"Banjur "},
    {U"Manawa ",U"Menawa "},
  },
  {
    44,
    16,
    "ka",
    {U"და ",U"ასევე "},
    {U"კონტექსტი"},
    {U"მაგრამ ",U"თუმცა "},
    {U"მაგალითები"},
    {U"თვისება",U"მოთხოვნა"},
    {U"მოცემული ",U"მოცემულია ",U"ვთქვათ "},
    {U"წესი"},
    {U"მაგალითად",U"მაგალითი",U"მაგ",U"სცენარი"},
    {U"სცენარის ნიმუში",U"სცენარის შაბლონი",U"ნიმუში",U"შაბლონი"},
    {U"მაშინ "},
    {U"როდესაც ",U"როცა ",U"როგორც კი ",U"თუ "},
  },
  {
    45,
    12,
    "kn",
    {U"ಮತ್ತು "},
    {U"ಹಿನ್ನೆಲೆ"},
    {U"ಆದರೆ "},
    {U"ಉದಾಹರಣೆಗಳು"},
    {U"ಹೆಚ್ಚಳ"},
    {U"ನೀಡಿದ "},
    {U"Rule"},
    {U"ಉದಾಹರಣೆ",U"ಕಥಾಸಾರಾಂಶ"},
    {U"ವಿವರಣೆ"},
    {U"ನಂತರ "},
    {U"ಸ್ಥಿತಿಯನ್ನು "},
  },
  {
    46,
    7,
    "ko",
    {U"그리고"},
    {U"배경"},
    {U"하지만",U"단"},
    {U"예"},
    {U"기능"},
    {U"조건",U"먼저"},
    {U"Rule"},
    {U"시나리오"},
    {U"시나리오 개요"},
    {U"그러면"},
    {U"만일",U"만약"},
  },
  {
    47,
    20,
    "lt",
    {U"Ir "},
    {U"Kontekstas"},
    {U"Bet "},
    {U"Pavyzdžiai",U"Scenarijai",U"Variantai"},
    {U"Savybė"},
    {U"Duota "},
    {U"Rule"},
    {U"Pavyzdys",U"Scenarijus"},
    {U"Scenarijaus šablonas"},
    {U"Tada "},
    {U"Kai "},
  },
  {
    48,
    18,
    "lu",
    {U"an ",U"a "},
    {U"Hannergrond"},
    {U"awer ",U"mä "},
    {U"Beispiller"},
    {U"Funktionalitéit"},
    {U"ugeholl "},
    {U"Rule"},
    {U"Beispill",U"Szenario"},
    {U"Plang vum Szenario"},
    {U"dann "},
    {U"wann "},
  },
  {
    49,
    21,
    "lv",
    {U"Un "},
    {U"Konteksts",U"Situācija"},
    {U"Bet "},
    {U"Piemēri",U"Paraugs"},
    {U"Funkcionalitāte",U"Fīča"},
    {U"Kad "},
    {U"Rule"},
    {U"Piemērs",U"Scenārijs"},
    {U"Scenārijs pēc parauga"},
    {U"Tad "},
    {U"Ja "},
  },
  {
    50,
    20,
    "mk-Cyrl",
    {U"И "},
    {U"Контекст",U"Содржина"},
    {U"Но "},
    {U"Примери",U"Сценарија"},
    {U"Функционалност",U"Бизнис потреба",U"Можност"},
    {U"Дадено ",U"Дадена "},
    {U"Rule"},
    {U"Пример",U"Сценарио",U"На пример"},
    {U"Преглед на сценарија",U"Скица",U"Концепт"},
    {U"Тогаш "},
    {U"Кога "},
  },
  {
    51,
    20,
    "mk-Latn",
    {U"I "},
    {U"Kontekst",U"Sodrzhina"},
    {U"No "},
    {U"Primeri",U"Scenaria"},
    {U"Funkcionalnost",U"Biznis potreba",U"Mozhnost"},
    {U"Dadeno ",U"Dadena "},
    {U"Rule"},
    {U"Scenario",U"Na primer"},
    {U"Pregled na scenarija",U"Skica",U"Koncept"},
    {U"Togash "},
    {U"Koga "},
  },
  {
    52,
    19,
    "mn",
    {U"Мөн ",U"Тэгээд "},
    {U"Агуулга"},
    {U"Гэхдээ ",U"Харин "},
    {U"Тухайлбал"},
    {U"Функц",U"Функционал"},
    {U"Өгөгдсөн нь ",U"Анх "},
    {U"Rule"},
    {U"Сценар"},
    {U"Сценарын төлөвлөгөө"},
    {U"Тэгэхэд ",U"Үүний дараа "},
    {U"Хэрэв "},
  },
  {
    53,
    16,
    "ne",
    {U"र ",U"अनि "},
    {U"पृष्ठभूमी"},
    {U"तर "},
    {U"उदाहरण",U"उदाहरणहरु"},
    {U"सुविधा",U"विशेषता"},
    {U"दिइएको ",U"दिएको ",U"यदि "},
    {U"नियम"},
    {U"परिदृश्य"},
    {U"परिदृश्य रूपरेखा"},
    {U"त्यसपछि ",U"अनी "},
    {U"जब "},
  },
  {
    54,
    17,
    "nl",
    {U"En "},
    {U"Achtergrond"},
    {U"Maar "},
    {U"Voorbeelden"},
    {U"Functionaliteit"},
    {U"Gegeven ",U"Stel "},
    {U"Rule"},
    {U"Voorbeeld",U"Scenario"},
    {U"Abstract Scenario"},
    {U"Dan "},
    {U"Als ",U"Wanneer "},
  },
  {
    55,
    17,
    "no",
    {U"Og "},
    {U"Bakgrunn"},
    {U"Men "},
    {U"Eksempler"},
    {U"Egenskap"},
    {U"Gitt "},
    {U"Regel"},
    {U"Eksempel",U"Scenario"},
    {U"Scenariomal",U"Abstrakt Scenario"},
    {U"Så "},
    {U"Når "},
  },
  {
    56,
    14,
    "pa",
    {U"ਅਤੇ "},
    {U"ਪਿਛੋਕੜ"},
    {U"ਪਰ "},
    {U"ਉਦਾਹਰਨਾਂ"},
    {U"ਖਾਸੀਅਤ",U"ਮੁਹਾਂਦਰਾ",U"ਨਕਸ਼ ਨੁਹਾਰ"},
    {U"ਜੇਕਰ ",U"ਜਿਵੇਂ ਕਿ "},
    {U"Rule"},
    {U"ਉਦਾਹਰਨ",U"ਪਟਕਥਾ"},
    {U"ਪਟਕਥਾ ਢਾਂਚਾ",U"ਪਟਕਥਾ ਰੂਪ ਰੇਖਾ"},
    {U"ਤਦ "},
    {U"ਜਦੋਂ "},
  },
  {
    57,
    19,
    "pl",
    {U"Oraz ",U"I "},
    {U"Założenia"},
    {U"Ale "},
    {U"Przykłady"},
    {U"Właściwość",U"Funkcja",U"Aspekt",U"Potrzeba biznesowa"},
    {U"Zakładając ",U"Mając ",U"Zakładając, że "},
    {U"Zasada",U"Reguła"},
    {U"Przykład",U"Scenariusz"},
    {U"Szablon scenariusza"},
    {U"Wtedy "},
    {U"Jeżeli ",U"Jeśli ",U"Gdy ",U"Kiedy "},
  },
  {
    58,
    21,
    "pt",
    {U"E "},
    {U"Contexto",U"Cenário de Fundo",U"Cenario de Fundo",U"Fundo"},
    {U"Mas "},
    {U"Exemplos",U"Cenários",U"Cenarios"},
    {U"Funcionalidade",U"Característica",U"Caracteristica"},
    {U"Dado ",U"Dada ",U"Dados ",U"Dadas "},
    {U"Regra"},
    {U"Exemplo",U"Cenário",U"Cenario"},
    {U"Esquema do Cenário",U"Esquema do Cenario",U"Delineação do Cenário",U"Delineacao do Cenario"},
    {U"Então ",U"Entao "},
    {U"Quando "},
  },
  {
    59,
    18,
    "ro",
    {U"Si ",U"Și ",U"Şi "},
    {U"Context"},
    {U"Dar "},
    {U"Exemple"},
    {U"Functionalitate",U"Funcționalitate",U"Funcţionalitate"},
    {U"Date fiind ",U"Dat fiind ",U"Dată fiind",U"Dati fiind ",U"Dați fiind ",U"Daţi fiind "},
    {U"Rule"},
    {U"Exemplu",U"Scenariu"},
    {U"Structura scenariu",U"Structură scenariu"},
    {U"Atunci "},
    {U"Cand ",U"Când "},
  },
  {
    60,
    18,
    "ru",
    {U"И ",U"К тому же ",U"Также "},
    {U"Предыстория",U"Контекст"},
    {U"Но ",U"А ",U"Иначе "},
    {U"Примеры"},
    {U"Функция",U"Функциональность",U"Функционал",U"Свойство",U"Фича"},
    {U"Допустим ",U"Дано ",U"Пусть "},
    {U"Правило"},
    {U"Пример",U"Сценарий"},
    {U"Структура сценария",U"Шаблон сценария"},
    {U"То ",U"Затем ",U"Тогда "},
    {U"Когда ",U"Если "},
  },
  {
    61,
    15,
    "sk",
    {U"A ",U"A tiež ",U"A taktiež ",U"A zároveň "},
    {U"Pozadie"},
    {U"Ale "},
    {U"Príklady"},
    {U"Požiadavka",U"Funkcia",U"Vlastnosť"},
    {U"Pokiaľ ",U"Za predpokladu "},
    {U"Rule"},
    {U"Príklad",U"Scenár"},
    {U"Náčrt Scenáru",U"Náčrt Scenára",U"Osnova Scenára"},
    {U"Tak ",U"Potom "},
    {U"Keď ",U"Ak "},
  },
  {
    62,
    19,
    "sl",
    {U"In ",U"Ter "},
    {U"Kontekst",U"Osnova",U"Ozadje"},
    {U"Toda ",U"Ampak ",U"Vendar "},
    {U"Primeri",U"Scenariji"},
    {U"Funkcionalnost",U"Funkcija",U"Možnosti",U"Moznosti",U"Lastnost",U"Značilnost"},
    {U"Dano ",U"Podano ",U"Zaradi ",U"Privzeto "},
    {U"Rule"},
    {U"Primer",U"Scenarij"},
    {U"Struktura scenarija",U"Skica",U"Koncept",U"Oris scenarija",U"Osnutek"},
    {U"Nato ",U"Potem ",U"Takrat "},
    {U"Ko ",U"Ce ",U"Če ",U"Kadar "},
  },
  {
    63,
    19,
    "sr-Cyrl",
    {U"И "},
    {U"Контекст",U"Основа",U"Позадина"},
    {U"Али "},
    {U"Примери",U"Сценарији"},
    {U"Функционалност",U"Могућност",U"Особина"},
    {U"За дато ",U"За дате ",U"За дати "},
    {U"Правило"},
    {U"Пример",U"Сценарио",U"Пример"},
    {U"Структура сценарија",U"Скица",U"Концепт"},
    {U"Онда "},
    {U"Када ",U"Кад "},
  },
  {
    64,
    19,
    "sr-Latn",
    {U"I "},
    {U"Kontekst",U"Osnova",U"Pozadina"},
    {U"Ali "},
    {U"Primeri",U"Scenariji"},
    {U"Funkcionalnost",U"Mogućnost",U"Mogucnost",U"Osobina"},
    {U"Za dato ",U"Za date ",U"Za dati "},
    {U"Pravilo"},
    {U"Scenario",U"Primer"},
    {U"Struktura scenarija",U"Skica",U"Koncept"},
    {U"Onda "},
    {U"Kada ",U"Kad "},
  },
  {
    65,
    17,
    "sv",
    {U"Och "},
    {U"Bakgrund"},
    {U"Men "},
    {U"Exempel"},
    {U"Egenskap"},
    {U"Givet "},
    {U"Regel"},
    {U"Scenario"},
    {U"Abstrakt Scenario",U"Scenariomall"},
    {U"Så "},
    {U"När "},
  },
  {
    66,
    18,
    "ta",
    {U"மேலும்  ",U"மற்றும் "},
    {U"பின்னணி"},
    {U"ஆனால்  "},
    {U"எடுத்துக்காட்டுகள்",U"காட்சிகள்",U"நிலைமைகளில்"},
    {U"அம்சம்",U"வணிக தேவை",U"திறன்"},
    {U"கொடுக்கப்பட்ட "},
    {U"Rule"},
    {U"உதாரணமாக",U"காட்சி"},
    {U"காட்சி சுருக்கம்",U"காட்சி வார்ப்புரு"},
    {U"அப்பொழுது "},
    {U"எப்போது "},
  },
  {
    67,
    21,
    "th",
    {U"และ "},
    {U"แนวคิด"},
    {U"แต่ "},
    {U"ชุดของตัวอย่าง",U"ชุดของเหตุการณ์"},
    {U"โครงหลัก",U"ความต้องการทางธุรกิจ",U"ความสามารถ"},
    {U"กำหนดให้ "},
    {U"Rule"},
    {U"เหตุการณ์"},
    {U"สรุปเหตุการณ์",U"โครงสร้างของเหตุการณ์"},
    {U"ดังนั้น "},
    {U"เมื่อ "},
  },
  {
    68,
    14,
    "te",
    {U"మరియు "},
    {U"నేపథ్యం"},
    {U"కాని "},
    {U"ఉదాహరణలు"},
    {U"గుణము"},
    {U"చెప్పబడినది "},
    {U"Rule"},
    {U"ఉదాహరణ",U"సన్నివేశం"},
    {U"కథనం"},
    {U"అప్పుడు "},
    {U"ఈ పరిస్థితిలో "},
  },
  {
    69,
    16,
    "tlh",
    {U"'ej ",U"latlh "},
    {U"mo'"},
    {U"'ach ",U"'a "},
    {U"ghantoH",U"lutmey"},
    {U"Qap",U"Qu'meH 'ut",U"perbogh",U"poQbogh malja'",U"laH"},
    {U"ghu' noblu' ",U"DaH ghu' bejlu' "},
    {U"Rule"},
    {U"lut"},
    {U"lut chovnatlh"},
    {U"vaj "},
    {U"qaSDI' "},
  },
  {
    70,
    15,
    "tr",
    {U"Ve "},
    {U"Geçmiş"},
    {U"Fakat ",U"Ama "},
    {U"Örnekler"},
    {U"Özellik"},
    {U"Diyelim ki "},
    {U"Kural"},
    {U"Örnek",U"Senaryo"},
    {U"Senaryo taslağı"},
    {U"O zaman "},
    {U"Eğer ki "},
  },
  {
    71,
    20,
    "tt",
    {U"Һәм ",U"Вә "},
    {U"Кереш"},
    {U"Ләкин ",U"Әмма "},
    {U"Үрнәкләр",U"Мисаллар"},
    {U"Мөмкинлек",U"Үзенчәлеклелек"},
    {U"Әйтик "},
    {U"Rule"},
    {U"Сценарий"},
    {U"Сценарийның төзелеше"},
    {U"Нәтиҗәдә "},
    {U"Әгәр "},
  },
  {
    72,
    18,
    "uk",
    {U"І ",U"А також ",U"Та "},
    {U"Передумова"},
    {U"Але "},
    {U"Приклади"},
    {U"Функціонал"},
    {U"Припустимо ",U"Припустимо, що ",U"Нехай ",U"Дано "},
    {U"Rule"},
    {U"Приклад",U"Сценарій"},
    {U"Структура сценарію"},
    {U"То ",U"Тоді "},
    {U"Якщо ",U"Коли "},
  },
  {
    73,
    17,
    "ur",
    {U"اور "},
    {U"پس منظر"},
    {U"لیکن "},
    {U"مثالیں"},
    {U"صلاحیت",U"کاروبار کی ضرورت",U"خصوصیت"},
    {U"اگر ",U"بالفرض ",U"فرض کیا "},
    {U"Rule"},
    {U"منظرنامہ"},
    {U"منظر نامے کا خاکہ"},
    {U"پھر ",U"تب "},
    {U"جب "},
  },
  {
    74,
    20,
    "uz",
    {U"Ва "},
    {U"Тарих"},
    {U"Лекин ",U"Бирок ",U"Аммо "},
    {U"Мисоллар"},
    {U"Функционал"},
    {U"Belgilangan "},
    {U"Rule"},
    {U"Сценарий"},
    {U"Сценарий структураси"},
    {U"Унда "},
    {U"Агар "},
  },
  {
    75,
    16,
    "vi",
    {U"Và "},
    {U"Bối cảnh"},
    {U"Nhưng "},
    {U"Dữ liệu"},
    {U"Tính năng"},
    {U"Biết ",U"Cho "},
    {U"Rule"},
    {U"Tình huống",U"Kịch bản"},
    {U"Khung tình huống",U"Khung kịch bản"},
    {U"Thì "},
    {U"Khi "},
  },
  {
    76,
    4,
    "zh-CN",
    {U"而且",U"并且",U"同时"},
    {U"背景"},
    {U"但是"},
    {U"例子"},
    {U"功能"},
    {U"假如",U"假设",U"假定"},
    {U"Rule",U"规则"},
    {U"场景",U"剧本"},
    {U"场景大纲",U"剧本大纲"},
    {U"那么"},
    {U"当"},
  },
  {
    77,
    4,
    "zh-TW",
    {U"而且",U"並且",U"同時"},
    {U"背景"},
    {U"但是"},
    {U"例子"},
    {U"功能"},
    {U"假如",U"假設",U"假定"},
    {U"Rule"},
    {U"場景",U"劇本"},
    {U"場景大綱",U"劇本大綱"},
    {U"那麼"},
    {U"當"},
  },
  {
    78,
    17,
    "mr",
    {U"आणि ",U"तसेच "},
    {U"पार्श्वभूमी"},
    {U"पण ",U"परंतु "},
    {U"उदाहरण"},
    {U"वैशिष्ट्य",U"सुविधा"},
    {U"जर",U"दिलेल्या प्रमाणे "},
    {U"नियम"},
    {U"परिदृश्य"},
    {U"परिदृश्य रूपरेखा"},
    {U"मग ",U"तेव्हा "},
    {U"जेव्हा "},
  },
  {
    79,
    11,
    "amh",
    {U"እና "},
    {U"ቅድመ ሁኔታ",U"መነሻ",U"መነሻ ሀሳብ"},
    {U"ግን "},
    {U"ምሳሌዎች",U"ሁናቴዎች"},
    {U"ስራ",U"የተፈለገው ስራ",U"የሚፈለገው ድርጊት"},
    {U"የተሰጠ "},
    {U"ህግ"},
    {U"ምሳሌ",U"ሁናቴ"},
    {U"ሁናቴ ዝርዝር",U"ሁናቴ አብነት"},
    {U"ከዚያ "},
    {U"መቼ "},
  },
};

const DialectIndex Dialect::name_to_index(const LanguageString &language) {
  switch (language[0]) {
  case 'a':
    if (language == "af") return 1;
    if (language == "am") return 2;
    if (language == "an") return 3;
    if (language == "ar") return 4;
    if (language == "ast") return 5;
    if (language == "az") return 6;
    if (language == "amh") return 79;
    break;
  case 'b':
    if (language == "be") return 7;
    if (language == "bg") return 8;
    if (language == "bm") return 9;
    if (language == "bs") return 10;
    break;
  case 'c':
    if (language == "ca") return 11;
    if (language == "cs") return 12;
    if (language == "cy-GB") return 13;
    break;
  case 'd':
    if (language == "da") return 14;
    if (language == "de") return 15;
    break;
  case 'e':
    if (language == "el") return 16;
    if (language == "em") return 17;
    if (language == "en") return 18;
    if (language == "en-Scouse") return 19;
    if (language == "en-au") return 20;
    if (language == "en-lol") return 21;
    if (language == "en-old") return 22;
    if (language == "en-pirate") return 23;
    if (language == "en-tx") return 24;
    if (language == "eo") return 25;
    if (language == "es") return 26;
    if (language == "et") return 27;
    break;
  case 'f':
    if (language == "fa") return 28;
    if (language == "fi") return 29;
    if (language == "fr") return 30;
    break;
  case 'g':
    if (language == "ga") return 31;
    if (language == "gj") return 32;
    if (language == "gl") return 33;
    break;
  case 'h':
    if (language == "he") return 34;
    if (language == "hi") return 35;
    if (language == "hr") return 36;
    if (language == "ht") return 37;
    if (language == "hu") return 38;
    break;
  case 'i':
    if (language == "id") return 39;
    if (language == "is") return 40;
    if (language == "it") return 41;
    break;
  case 'j':
    if (language == "ja") return 42;
    if (language == "jv") return 43;
    break;
  case 'k':
    if (language == "ka") return 44;
    if (language == "kn") return 45;
    if (language == "ko") return 46;
    break;
  case 'l':
    if (language == "lt") return 47;
    if (language == "lu") return 48;
    if (language == "lv") return 49;
    break;
  case 'm':
    if (language == "mk-Cyrl") return 50;
    if (language == "mk-Latn") return 51;
    if (language == "mn") return 52;
    if (language == "mr") return 78;
    break;
  case 'n':
    if (language == "ne") return 53;
    if (language == "nl") return 54;
    if (language == "no") return 55;
    break;
  case 'p':
    if (language == "pa") return 56;
    if (language == "pl") return 57;
    if (language == "pt") return 58;
    break;
  case 'r':
    if (language == "ro") return 59;
    if (language == "ru") return 60;
    break;
  case 's':
    if (language == "sk") return 61;
    if (language == "sl") return 62;
    if (language == "sr-Cyrl") return 63;
    if (language == "sr-Latn") return 64;
    if (language == "sv") return 65;
    break;
  case 't':
    if (language == "ta") return 66;
    if (language == "th") return 67;
    if (language == "te") return 68;
    if (language == "tlh") return 69;
    if (language == "tr") return 70;
    if (language == "tt") return 71;
    break;
  case 'u':
    if (language == "uk") return 72;
    if (language == "ur") return 73;
    if (language == "uz") return 74;
    break;
  case 'v':
    if (language == "vi") return 75;
    break;
  case 'z':
    if (language == "zh-CN") return 76;
    if (language == "zh-TW") return 77;
    break;
  }
  return 0;
}

const Dialect* Dialect::for_index(DialectIndex index) {
  if (index <= 0 || index > 79) {
    return 0;
  }
  return &DIALECTS[index - 1];
}

#endif /* GHERKIN_DIALECT_CC_ */